### ISSUE TITLE
Version error and after fix it

### ISSUE THREAD

**Issue by Alan-Yan-CanMeng** [alec016/CM-ArsNouveau#2]
When use Custom-Machinery-ArsNouveau-1.19.2-1.0.0 and ars_nouveau-1.19.2-3.22.3
&emsp;error: https://mclo.gs/b9bAGoQ
Ars Nouveau on curseforge and modrinth is 3.22.3, I think the corresponding version on maven is 3.22.3.680
After modify mods.toml `versionRange = "[3.22.3.681,)" => versionRange = "[3.22.3,)"`, Another error occurred:
&emsp;error: https://mclo.gs/AdCGpa9
&emsp;crash report: https://mclo.gs/nKTT7f9

**Comment by Alan-Yan-CanMeng** [comment]
oh, this is the log and crash reportwhen I use jei:
&emsp;error: https://mclo.gs/TSMcbp6
&emsp;crash report: https://mclo.gs/iTIUmOf

**Comment by alec016** [comment]
I'm working to fix it in the next update. Maybe i need to change the entire structure of the mod.
